### ISSUE TITLE
Use autogenerated tdlib libraries to enable CI

### ISSUE THREAD

**Issue by dorak88783** [aCLr/rust-tdlib#1]
Hi, I saw you disabled the CI steps in `https://github.com/aCLr/rust-tdlib/blob/master/.github/workflows/rust.yml` because of "tests disables in case of unavailable tdlib =(".

I just made a github action flow that compiles tdlib, it's at https://github.com/dorak88783/tdlib-builder. If you want you can use this to get a tdlib library available to run the tests. I have it working in a private repo. If you like this idea/flow I can try to make it work in this repo and make PR. What do you think?

**Comment by antonio-antuan** [comment]
I wanted to make this, but do not have enough time.
Your action flow looks great but currently it uses tdlib 1.7.1. I'm just working on that version and it is not finished yet.

It would be better to specify particular tdlib version within particular rust-tdlib branch. 

Also I think that if we will build tdlib each time it can take a lot of extra time. What if we will use a docker-image with already build tdlib?

**Comment by dorak88783** [comment]
I think I could make it such that it compiles different versions, I can check. Which one do you prefer right now?

In my view, the TDlib library compilation only happens once, in this `td-builder` repository. You can just clone this repository in your action and get the library from there, which is quick. I didn't propose to copy my action flow to your action flow.

**Comment by antonio-antuan** [comment]
Ok. I almost finish 1.7.0 support and going to implement tests run with github actions as soon as possible.

**Comment by antonio-antuan** [comment]
@dorak88783 I have just tried to use library from your repo and build fails with `/usr/bin/ld: cannot find -ltdjson`. 
I think that the most right config may looks like that:
`RUSTFLAGS: "-C link-args=-Wl,-rpath,tdlib-builder/lib"`
Here is more logs: https://github.com/aCLr/rust-tdlib/runs/2222307705.
Could you provide linker args that you use?

**Comment by dorak88783** [comment]
It took me some time to get it working as well :) I now have

`RUSTFLAGS: "-C link-args=-Wl,-rpath=./tdlib-builder/lib/,--verbose -L./tdlib-builder/lib/"`

I think the `-L` argument is the only part missing from your command.

**Comment by antonio-antuan** [comment]
Great, I've just checked it on my laptop and it works fine thanks.
I will integrate it in a couple of hours.

вт, 30 мар. 2021 г. в 10:37, dorak88783 ***@***.***>:

**Comment by antonio-antuan** [comment]
ok, it's done. thanks for your help.
