### ISSUE TITLE
waiting for encryption key. What encryption key?

### ISSUE THREAD

**Issue by TheK0tYaRa** [aCLr/rust-tdlib#11]
Explain it to me as if i am copying code from the example file (as i am)

**Comment by TheK0tYaRa** [comment]
Googling didn't help if you wanted to ask me to do so. It needs more documentation about where to get said key IF it's receivable.

**Comment by antonio-antuan** [comment]
You can check tdlib original documentation: https://core.telegram.org/tdlib/getting-started#user-authorization:

> The second received authorization state is always authorizationStateWaitEncryptionKey. When it is received, the database encryption key should be provided through a call to checkDatabaseEncryptionKey. For most mobile apps, you can provide an empty database encryption key here (more info).

**Comment by antonio-antuan** [comment]
And yes, here is detailed usage: https://github.com/tdlib/td/issues/188#issuecomment-379536139

**Comment by TheK0tYaRa** [comment]
So manual input is required once or more, or it should be done via `set_database_encryption_key()` ?
Oh wait, that can't do the job. So will there be a function that does it automatically or is it a one-off?

**Comment by antonio-antuan** [comment]
As tdlib docs said, encryption key has to be set on each app start. 

There are several ways to do it with rust-tdlib:
1. manually (ConsoleAuthStateHandler)
2. pass it from some kind of config or anything else
3. `AuthStateHandlerWithEmptyEncryptionKey impl AuthStateHandler`: you can write your own implementation of `AuthStateHandler` and it can always pass empty encryption key.

For example, [here](https://github.com/aCLr/rust-tdlib/blob/master/examples/handle_auth_state.rs#L49) I pass empty encryption key with channel-like handler.

**Comment by TheK0tYaRa** [comment]
Understood, thanks!
