### ISSUE TITLE
Question: How do you get messages as they come in?

### ISSUE THREAD

**Issue by ibortnik** [aCLr/rust-tdlib#13]
I wish to get new messages as they arrive in a chat.
I see `types:::UpdateNewMessage` but no `update_new_message()` function..

What do I use `UpdateNewMessage` with?

**Comment by antonio-antuan** [comment]
You can get new messages with mpsc::channel if you pass sender to `ClientBuilder::with_updates_sender`. See [this](https://github.com/aCLr/rust-tdlib/blob/40262849d87608931f22d0bbfd5baa0b410461ce/examples/read_updates.rs#L34) for more details.

**Comment by ibortnik** [comment]
Thanks!
