### ISSUE TITLE
unknown variant Json fail: Error("unknown variant `Chat`, expected one of `_Default`, `messageSenderChat`, `messageSenderUser`",

### ISSUE THREAD

**Issue by makorne** [aCLr/rust-tdlib#18]
Hi! Thank you for the great crate!

I try to save/restore messages as json files.

serde = {version = "1", features = ["derive"]}
serde_json = "1"

```
                Update::NewMessage(new_message) => {
                      let message_json = serde_json::to_string(new_message.message()).expect("Can't serialize json");
                      let file_dir = "/tmp/test.json";
                      let mut file = File::create(file_dir).await?;
                      file.write_all(message_json.as_bytes()).await?;

                      let file = std::fs::File::open(file_dir).expect("Cant open file");
                      let mut reader = std::io::BufReader::new(file);
                      let read_message: Message = serde_json::from_reader(reader).expect("Json fail");
                }
```
Saved json looks good but the  serde_json::from_reader throws error

` Json fail: Error("unknown variant `Chat`, expected one of `_Default`, `messageSenderChat`, `messageSenderUser`", line: 1, column: 77)`

The same error for other updates for example Supergroup 

`Json fail: Error("unknown variant `Member`, expected one of `_Default`, `chatMemberStatusAdministrator`, `chatMemberStatusBanned`, `chatMemberStatusCreator`, `chatMemberStatusLeft`, `chatMemberStatusMember`, `chatMemberStatusRestricted`", line: 1, column: 118)`

May be for successful deserializing your crate enums need something like #[serde(untagged)]  like in this [post](https://stackoverflow.com/questions/71011592/deserializing-an-unknown-enum) ?
 
How to save/restore messages as json files?

**Comment by antonio-antuan** [comment]
Hi! Thanks for the issue.
Interesting. I have just gotten totally different error... Could you provide json data, that produces the error? If you can, do not forget to remove all sensitive data: replace`*id` field's data... and so on :)

Answering your question, for now there is only one way correct to save json and such a way you have provided.
Another option is to use tdlib (the original library) logging system: rust_tdlib::set_log_file_path or the modern way `client.SetLogStream`. But yes, it will store all the data in the log file.

I can try to find a way to provide the main json data or at least `serde_json::Value` but I can't say when it will be implemented.

For now I want to fix your error and give you (and other users) possibility to store json this way.

**Comment by makorne** [comment]
> I have just gotten totally different error...

Interesting.  And what about "sender_id":{"@type":"Chat" in your json? 
Is this @type  "messageSenderChat"  or "Chat"?

Like in my jsons : 

```
{"@extra":null,"@client_id":null,"id":88441,"sender_id":{"@type":"Chat","@extra":null,"@client_id":null,"chat_id":-100130},
  "chat_id":-100130,"sending_state":null,"scheduling_state":null,"is_outgoing":false,"is_pinned":false,
  "can_be_edited":false,"can_be_forwarded":true,"can_be_saved":true,"can_be_deleted_only_for_self":false,"can_be_deleted_for_all_users":false,
  "can_get_statistics":false,"can_get_message_thread":false,"can_get_viewers":false,"can_get_media_timestamp_links":true,"has_timestamped_media":true,
  "is_channel_post":true,"contains_unread_mention":false,"date":1660457540,"edit_date":0,"forward_info":null,
  "interaction_info":{"@extra":null,"@client_id":null,"view_count":16,"forward_count":0,"reply_info":null},
  "reply_in_chat_id":0,"reply_to_message_id":0,"message_thread_id":0,"ttl":0,"ttl_expires_in":0.0,"via_bot_user_id":0,
  "author_signature":"","media_album_id":0,"restriction_reason":"","content":{"@type":"MessagePhoto","@extra":null,"@client_id":null,
	  "photo":{"@extra":null,"@client_id":null,"has_stickers":false,
		  "minithumbnail":{"@extra":null,"@client_id":null,"width":40,"height":27,"data":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAbACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDYqN5NjAbHOfQVCN86hzIyKegBxgU12kRPlcuueCeoPagC2WAHPFVlfzZy27hDwOmR6/nT9wdtoycjlvaq5LvKkqtsjPyg98ev5igC8OnNFQF3h2sz7oycEnqKKAITgwGCRtrDjGetRmESYhjc7urEHIWrYRXuXLqGwoxkU6AAK2ABlj0FADLeB4omjdg2c81GsSTRCGQ7Xj4wD+tXKaUV/vKDj1FAFaQK6i2U5Jxk+gFFWgqpwoAHsKKAP//Z"},"sizes":[{"@extra":null,"@client_id":null,"type":"m","photo":{"@extra":null,"@client_id":null,"id":1064,"size":19501,"expected_size":19501,"local":{"@extra":null,"@client_id":null,"path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@extra":null,"@client_id":null,"id":"AgACAgIAAx0CTayHXwABAUl4YviSboJSSm11xsfCipYPVUJn9GgAAie8MRsdislL0vNMz8VTKH4BAAMCAANtAAMjBA",
			  "unique_id":"AQADJ7wxGx2KyUty","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":19501}},"width":320,"height":214,"progressive_sizes":[]},
			  {"@extra":null,"@client_id":null,"type":"y","photo":{"@extra":null,"@client_id":null,"id":1066,"size":72613,"expected_size":72613,"local":{"@extra":null,"@client_id":null,"path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@extra":null,"@client_id":null,"id":"AgACAgIAAx0CTayHXwABAUl4YviSboJSSm11xsfCipYPVUJn9GgAAie8MRsdislL0vNMz8VTKH4BAAMCAAN5AAMjBA","unique_id":"AQADJ7wxGx2KyUt-","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":72613}},
				  "width":1034,"height":693,"progressive_sizes":[7857,20719,29390,44277]},{"@extra":null,"@client_id":null,"type":"x",
			  "photo":{"@extra":null,"@client_id":null,"id":1065,"size":75503,"expected_size":75503,
				  "local":{"@extra":null,"@client_id":null,"path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},
				  "remote":{"@extra":null,"@client_id":null,"id":"AgACAgIAAx0CTayHXwABAUl4YviSboJSSm11xsfCipYPVUJn9GgAAie8MRsdislL0vNMz8VTKH4BAAMCAAN4AAMjBA","unique_id":"AQADJ7wxGx2KyUt9","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":75503}},
				  "width":800,"height":536,"progressive_sizes":[]}]},"caption":{"@extra":null,"@client_id":null,"text":"","entities":[]},"is_secret":false},"reply_markup":null}
```

**Comment by antonio-antuan** [comment]
The problem above is fixed in master branch. 
But yesterday I found another one and need to fix it before the new crate version. 
I hope to fix it in a couple of days.

**Comment by makorne** [comment]
This enum works now,
 But there is another error:

`Json fail: Error("invalid type: integer `0`, expected a string", line: 1, column: 914)`

I think in "media_album_id":0,

`{"@extra":null,"@client_id":null,"id":88599111111,"sender_id":{"@type":"messageSenderChat","@extra":null,"@client_id":null,"chat_id":-1001303111111},"chat_id":-1001303111111,"sending_state":null,"scheduling_state":null,"is_outgoing":false,"is_pinned":false,"can_be_edited":false,"can_be_forwarded":true,"can_be_saved":true,"can_be_deleted_only_for_self":false,"can_be_deleted_for_all_users":false,"can_get_statistics":false,"can_get_message_thread":false,"can_get_viewers":false,"can_get_media_timestamp_links":true,"has_timestamped_media":true,"is_channel_post":true,"contains_unread_mention":false,"date":1660557026,"edit_date":0,"forward_info":null,"interaction_info":{"@extra":null,"@client_id":null,"view_count":42,"forward_count":0,"reply_info":null},"reply_in_chat_id":0,"reply_to_message_id":0,"message_thread_id":0,"ttl":0,"ttl_expires_in":0.0,"via_bot_user_id":0,"author_signature":"","media_album_id":0,"restriction_reason":"","content":{"@type":"messagePhoto","@extra":null,"@client_id":null,"photo":{"@extra":null,"@client_id":null,"has_stickers":false,"minithumbnail":{"@extra":null,"@client_id":null,"width":40,"height":40,"data":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAoACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCaS5aclAxjUjqR1qEQRhQu4SN6mmQXJSbB4znn0qxJqQSJWAV9xwMZGaAIp08tMgAYOB+VMberZwNhxUsNz58rgpsI9Kp3BdJGHUUWVxWHzZRyemaKWBllULJnf0GRxRSaQWGzxbM7scH+E5/lULIcgkgjtwKtzW7Bi0cpTu3PH5UsWnySgObgMPpmmMrRyNHypAqQTg5Eoz6YFS3NqIkO3k+uaqiPht30o3BuxNmKN1bDc8iimlgdqlMtwAM0UrAWCS/I/hPT2omndkCwRiJj98g4oooegwhhCuT2PbOaga0kdzv4HrmiihMLE0NmkZDZJYUUUUAf/9k="},"sizes":[{"@extra":null,"@client_id":null,"type":"m","photo":{"@extra":null,"@client_id":null,"id":981,"size":40876,"expected_size":40876,"local":{"@extra":null,"@client_id":null,"path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@extra":null,"@client_id":null,"id":"AgACAgIAAx0CTayHXwABAUoPYvoXgQ9LBuijP5gQbjXUrN3NDRkAAmG-MRucMtBL2i7zqUHTtGYBAAMCAANtAAMjBA","unique_id":"AQADYb4xG5wy0Ety","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":40876}},"width":320,"height":320,"progressive_sizes":[]},{"@extra":null,"@client_id":null,"type":"x","photo":{"@extra":null,"@client_id":null,"id":982,"size":196919,"expected_size":196919,"local":{"@extra":null,"@client_id":null,"path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@extra":null,"@client_id":null,"id":"AgACAgIAAx0CTayHXwABAUoPYvoXgQ9LBuijP5gQbjXUrN3NDRkAAmG-MRucMtBL2i7zqUHTtGYBAAMCAAN4AAMjBA","unique_id":"AQADYb4xG5wy0Et9","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":196919}},"width":800,"height":800,"progressive_sizes":[]},{"@extra":null,"@client_id":null,"type":"y","photo":{"@extra":null,"@client_id":null,"id":983,"size":281206,"expected_size":281206,"local":{"@extra":null,"@client_id":null,"path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@extra":null,"@client_id":null,"id":"AgACAgIAAx0CTayHXwABAUoPYvoXgQ9LBuijP5gQbjXUrN3NDRkAAmG-MRucMtBL2i7zqUHTtGYBAAMCAAN5AAMjBA","unique_id":"AQADYb4xG5wy0Et-","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":281206}},"width":1280,"height":1280,"progressive_sizes":[21551,58911,94334,157669]}]},"caption":{"@extra":null,"@client_id":null,"text":"","entities":[]},"is_secret":false},"reply_markup":null}`

**Comment by antonio-antuan** [comment]
Yeap, this is the error. 
As you can see Telegram sends it as a string when serialization performed as a number. 
This is a deal: I need to change codegen to perform correct serialization for all the types with `super::_common::number_from_string`. Not a big deal, just need a bit of time.

```
#[serde(deserialize_with = "super::_common::number_from_string")]
#[serde(default)]
media_album_id: i64,
```

**Comment by antonio-antuan** [comment]
@makorne it's done. It would be great if you can check fixes before I release the new version.

**Comment by makorne** [comment]
I have just tested it!
All worked!!!
Great job!

**Comment by antonio-antuan** [comment]
0.4.1 has just released.
Thanks for your help.
