### ISSUE TITLE
cannot deserialize to update: Error("unknown variant `updateReactions`

### ISSUE THREAD

**Issue by makorne** [aCLr/rust-tdlib#22]
Hi! 
Thank you for your great crate!

But looks like it needs adding **updateReactions** and **updateAttachmentMenuBots** for solving errors

rust-tdlib-0.4.1/src/client/worker.rs   line 475

`cannot deserialize to update: Error("unknown variant `updateAttachmentMenuBots`, expected one of  `_Default`, `testUseUpdate`, `updateActiveNotifications`, `updateAnimatedEmojiMessageClicked`, `updateAnimationSearchParameters`, ... `updateUserFullInfo`, `updateUserPrivacySettingRules`, `updateUserStatus`, `updateUsersNearby`", line: 0, column: 0), data: "{\"@type\":\"updateAttachmentMenuBots\",\"bots\":[],\"@client_id\":1}"`

and the same for **updateFileDownloads**:

`cannot deserialize to update: Error("unknown variant `updateFileDownloads`, expected one of  `_Default`, `testUseUpdate`, `updateActiveNotifications`, `updateAnimatedEmojiMessageClicked`, `updateAnimationSearchParameters`, ... `updateUserFullInfo`, `updateUserPrivacySettingRules`, `updateUserStatus`, `updateUsersNearby`", line: 0, column: 0), data: "{\"@type\":\"updateFileDownloads\",\"total_size\":0,\"total_count\":0,\"downloaded_size\":0,\"@client_id\":1}"`

and for **updateChatAvailableReactions**:

`cannot deserialize to update: Error("unknown variant `updateChatAvailableReactions`, expected one of `_Default`, `testUseUpdate`, `updateActiveNotifications`, `updateAnimatedEmojiMessageClicked`, `updateAnimationSearchParameters`, ... `updateUserFullInfo`, `updateUserPrivacySettingRules`, `updateUserStatus`, `updateUsersNearby`", line: 0, column: 0), data: "{\"@type\":\"updateChatAvailableReactions\",\"chat_id\":777000,\"available_reactions\":[\"\\ud83d\\udc4d\",\"\\ud83d\\udc4e\",\"\\u2764\",\"\\ud83d\\udd25\",\"\\ud83e\\udd70\",\"\\ud83d\\udc4f\",\"\\ud83d\\ude01\",\"\\ud83e\\udd14\",\"\\ud83e\\udd2f\",\"\\ud83d\\ude31\",\"\\ud83e\\udd2c\",\"\\ud83d\\ude22\",\"\\ud83c\\udf89\",\"\\ud83e\\udd29\",\"\\ud83e\\udd2e\",\"\\ud83d\\udca9\",\"\\ud83d\\ude4f\",\"\\ud83d\\udc4c\",\"\\ud83d\\udd4a\",\"\\ud83e\\udd21\",\"\\ud83e\\udd71\",\"\\ud83e\\udd74\",\"\\ud83d\\ude0d\",\"\\ud83d\\udc33\",\"\\u2764\\u200d\\ud83d\\udd25\",\"\\ud83c\\udf1a\",\"\\ud83c\\udf2d\",\"\\ud83d\\udcaf\",\"\\ud83e\\udd23\",\"\\u26a1\",\"\\ud83c\\udf4c\",\"\\ud83c\\udfc6\",\"\\ud83d\\udc94\",\"\\ud83e\\udd28\",\"\\ud83d\\ude10\",\"\\ud83c\\udf53\",\"\\ud83c\\udf7e\",\"\\ud83d\\udc8b\",\"\\ud83d\\udd95\",\"\\ud83d\\ude08\",\"\\ud83d\\ude34\",\"\\ud83d\\ude2d\",\"\\ud83e\\udd13\",\"\\ud83d\\udc7b\",\"\\ud83d\\udc68\\u200d\\ud83d\\udcbb\",\"\\ud83d\\udc40\",\"\\ud83c\\udf83\",\"\\ud83d\\ude48\",\"\\ud83d\\ude07\",\"\\ud83d\\ude28\",\"\\ud83e\\udd1d\",\"\\u270d\",\"\\ud83e\\udd17\",\"\\ud83e\\udee1\"],\"@client_id\":1}"`

**Comment by antonio-antuan** [comment]
What version of tdlib do you use? Looks like it is master, instead of last released 1.8.0.

**Comment by makorne** [comment]
Ups...
Yes... Looks like my tdlib is too new... 
1.8.5   dated  31-Aug-2022

Thank you for prompt answer!
