### ISSUE TITLE
Why use outdated tdlib?

### ISSUE THREAD

**Issue by makorne** [aCLr/rust-tdlib#27]
Hi! 
Thank you for great crate!
  
Looks like we wrongly understand tglib releases. 

Just read tdlib developers explanation : ["The recommended commit to use would still be the last commit from the master branch."](https://github.com/tdlib/td/issues/1656#issuecomment-917622548)

The Bad news:

The 1.8.0 is NOT CURRENT version.
It is outdated, bugged and not updated around a year. 

Current stable and updated Tglib release is 1.8.9

So 1.8.0 has been outdated 9 versions back.
It is like using Windows 8 when all other use Windows 11.
 
Yes tdlib has had too many changes, but I think just now they are growing  fast.

The Good news:
Breaking changes are less frequent, only commits with **"Update layer to 137"** for example.

So I am afraid, you mission of fixing memory bugs like [libtdjson Memory Leak](https://github.com/antonio-antuan/rust-tdlib/issues/19) as well as any other bugs, has no point.
Because the current tdlib was updated  many times and that has already repaired many different bugs. 

So looks like it is better to use your great efforts for updating rust-tdlib to the current version of tdlib.

**Comment by antonio-antuan** [comment]
The good news:
I appreciate your attention very much.

The bad news:
It's better for you to know that I don't use the project currently at all so all the updates may be done if someone asks for them.

Considering your requests I plan to make requested changes as fast as it possible. 
Hope to see a more polite and proper message when it's done.
