### ISSUE TITLE
tokio concurrency with Client

### ISSUE THREAD

**Issue by moonstripe** [aCLr/rust-tdlib#28]
Hello,

I'm having an issue running concurrent instances of Client.

Here is the general control flow of my application:

```Rust
let list_of_chats: Vec<&str> = vec!["chat_1", "chat_2", ...];

    // let (sender, mut receiver) = tokio::sync::mpsc::channel::<Box<Update>>(10000);

    // Process all of this concurrently
    let mut list_of_futures = FuturesUnordered::new();

    for chat in list_of_chats {
        let client = Client::builder()
            .with_tdlib_parameters(
                TdlibParameters::builder()
                    .database_directory(chat)
                    .use_test_dc(false)
                    .api_id(std::env::var("API_ID").unwrap().parse::<i32>().unwrap())
                    .api_hash(std::env::var("API_HASH").unwrap())
                    .system_language_code("en")
                    .device_model("Desktop")
                    .system_version("Unknown")
                    .application_version(env!("CARGO_PKG_VERSION"))
                    .enable_storage_optimizer(true)
                    .build(),
            )
            // .with_updates_sender(sender)
            .build()
            .unwrap();

        let mut worker = Worker::builder().build().unwrap();

        worker.start();
    
        let client = worker.bind_client(client).await.unwrap();
    
        loop {
            if worker.wait_client_state(&client).await.unwrap() == ClientState::Opened {
                log::info!("client authorized");
                break;
            }
        }

        let i_s = pull_sources_from_channel_name(client.to_owned(), club);
        list_of_futures.push(i_s);

        client.stop().await.unwrap();

        loop {
            if worker.wait_client_state(&client).await.unwrap() == ClientState::Closed {
                log::info!("client1 closed");
                break;
            }
        }

        worker.stop();

    }

    while let Some(status_result) = list_of_futures.next().await {
        log::info!("{:#?}", status_result)
    }
```

When I run this with my API_ID and API_HASH, I get the following error:

```
[ 0][t 0][1677184963.310343980][Client.cpp:282] Receive must not be called simultaneously from two different threads, but this has just happened. Call it from a fixed thread, dedicated for updates and response processing.
```

What I'm getting from this message is that the receive method on the original Client binding can only be run on one thread, but is it possible to send requests concurrently and merely receive them blocked?

Otherwise, I really love this library and I prefer it so much to the Python implementation!

Keep up the good work, y'all!! <3

**Comment by antonio-antuan** [comment]
omg, lost the issue, sorry.

so you are right, the original library is totally sequential and does not support concurrent access to its api, at least when you try to create multiple worker instances.  
But you may try to create single instance of worker (which is right in any case) and access it asynchronously.
So, like this:
1. create single worker instance
2. create one client and bind it
3. create a future using `Client::get_whatever_you_want` and put it into a `list_of_futures` in a loop
4. the other logic.

**Comment by moonstripe** [comment]
No worries at all! Really appreciate the response.

I'll give it a shot this weekend, and I'll come back with any other issues I have. I _thought_ I tried something like this but I'll give it another shot.

Again, thanks so much for the work you've put into this.

**Comment by antonio-antuan** [comment]
@moonstripe any updates regarding the issue?

**Comment by moonstripe** [comment]
I just implemented it as you said today. Works excellently.

Again, thanks for all of your work!
