### ISSUE TITLE
Inability to handle authentication errors and change the authentication flow

### ISSUE THREAD

**Issue by melix99** [aCLr/rust-tdlib#6]
Correct me if I'm wrong, but with the current API it doesn't seem to be a way to handle errors when an authentication error occurs while in Worker::auth_client(). I know that I can make a custom AuthStateHandler, but I still can't find a way to detect for example when a wrong confirmation code is inserted.

Also, another thing that I would like from the API is the ability to change the phone number after I inserted one while authenticating. This is similar to e.g. Telegram Desktop that you can change the phone number after you inserted one (e.g after you notice you inserted the wrong one).

Btw great job with the project!

**Comment by antonio-antuan** [comment]
Hello. Sorry for a long waiting, I've got a lot (no-no-no REALLY a lot) of
private duties.

Well yes, you're right, currently there is no good way to handle wrong auth
code and any other auth error. The only one option is to listen updates and
get worker stopped: you can try it with `read_updates` example. And yes,
this is awful option. I need to think a bit to provide more convenient API.

And yes, currently there is no way to change phone number. The one way is
to stop auth_client future by wrap it with tokio::spawn and to call
`cancel` on it. And yes, it's awful option too. What we can do here...
well, for now I think that auth_client can be synchronous and return
`Client` struct immediately. Also `Client` can provide method `get_state`
that returns reference to a `ClientAuthState` struct with several methods
(stop, reset, is_authenticated, ...).
And I'm not sure but it looks like this change can be used to handle auth
errors.

What do you think about this?

сб, 1 мая 2021 г., 17:02 Marco Melorio ***@***.***>:

**Comment by antonio-antuan** [comment]
@melix99 Hi there
I've made almost what I mentioned above. You can try branch `state-changes` if you want. There is the new example names `handle_auth_errors`. 

I'm going to test that branch in my project and remove a bunch of new `unwrap()` calls ( :) ) before publish 0.3.0. It can take all this week. 
If you want to change something in new API - please let me know.
Thanks for your issue.

**Comment by melix99** [comment]
Hey! Really sorry for not replying to the other comment, I think that I didn't notice the notification.

Thanks for keeping the interest on fixing this issue. I've seen the `handle_auth_errors` example and the API seems fine to me. Unfortunately I already end up developing a custom tdlib rust client (which is basically a generator for the .tl file, so it doesn't have the more "high level" api that yours have) for my needs. But I'll definitely keep an eye on your project in case I'll need something easier to use than mine!

**Comment by antonio-antuan** [comment]
Yes I've seen it. And that's a good idea: simple api if you don't need strict types. I think that I'm going to do something like that. Or not. Depends on mood :)

Anyway thanks for your feedback.

**Comment by antonio-antuan** [comment]
0.3.0 with the new feature released.
